### ISSUE TITLE
Choose head remote

### ISSUE THREAD

**Issue by Korbeil** [hupkit/hupkit#57]
| Q                     | A
| --------------------- | -----
| Bug report?           | no
| Feature request?      | yes
| BC Break report?      | no
| RFC?                  | no

Hi, 
Is it possible to add a way to choose the head remote ? (and choose something different than `upstream`)

I can suggest you using the composer `extra` field to make configuration (like that it would be repository-wide only.

**Comment by Korbeil** [comment]
Btw, I'll be glad to help you out to make this work if it comply to what you think we have to do for this tool 😄

**Comment by sstok** [comment]
What is the use-case for this?

Upstream points to the "root" of the repository (not your own fork) and is used for determining the organization and repository. In fact, origin is only used for updating and cleaning-up of your own pull requests.

**Comment by Korbeil** [comment]
I'm maintaining some repositories where I use the repository as origin (I don't have fork for it).

But I'm also using it for repositories with a fork (and the upstream / origin usual case)

**Comment by sstok** [comment]
Since #108 it's possible to store addition configuration for the repository (with the repository itself), this might solve this use-case?

```yaml
# config.php in "_hubkit" branch (actual configuration is Php, yaml only used as example)
schema_version: 2

host: github.com
repository: 'rollerworks/search'
```
